export const GET_COURSES = "GET_COURSES";
export const GET_COURSE_DETAIL = "GET_COURSE_DETAIL";

export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_COURSE_BY_CATEGORIES = "GET_COURSE_BY_CATEGORIES";
export const SET_CATE = "SET_CATE";

export const SEARCH_COURSE = "SEARCH_COURSE";